"""watermark-remover: xoá nhãn công cụ/AI khỏi file .docx đầu ra.

File .docx sinh bằng thư viện thường mang dấu vết của trình tạo trong metadata (không hiển thị
trên trang nhưng xem được ở File → Info / Properties):
  - docProps/core.xml: mô tả "Tạo bởi …", "generated by python-docx", người sửa cuối, ngày tạo
    lấy từ template (2013), từ khoá, danh mục;
  - docProps/app.xml: tên ứng dụng, phiên bản, template, công ty, tổng thời gian soạn;
  - docProps/thumbnail.jpeg: ảnh thu nhỏ của template gốc, không khớp nội dung thật;
  - các đoạn văn chỉ gồm nhãn kiểu "Generated with …", "Tạo bởi AI" trong thân bài/header/footer.

Module này làm sạch các phần trên ở mức gói ZIP nên áp dụng được cho mọi file .docx, không chỉ
file do wordreport tạo. Nội dung báo cáo (chữ, bảng, hình, định dạng) được giữ nguyên.

Dùng:  watermark-remover bao-cao.docx [thêm file...] [-o out.docx] [--author "Tên"]
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from lxml import etree

NS = {
    "cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcterms": "http://purl.org/dc/terms/",
    "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    "ep": "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties",
    "w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main",
    "rel": "http://schemas.openxmlformats.org/package/2006/relationships",
    "ct": "http://schemas.openxmlformats.org/package/2006/content-types",
}

THUMBNAIL_REL = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail"

# Tên trình tạo / thư viện hay xuất hiện trong metadata
GENERATOR_PATTERN = re.compile(
    r"python-docx|docx4j|docxtpl|openpyxl|pandoc|aspose|wordreport|\bLLM\b|\bMCP\b|"
    r"\bAI\b|ChatGPT|OpenAI|Claude|Anthropic|Gemini|Copilot|generated|tạo bởi|tạo tự động",
    re.IGNORECASE,
)

# Đoạn văn CHỈ gồm nhãn trình tạo/AI. Bắt buộc có tên công cụ/AI để không xoá nhầm dòng tác giả thật
# ("Written by John Smith") hay câu có nội dung khác.
_TOOL = (r"\[?(ai|an ai|trí tuệ nhân tạo|artificial intelligence|chatgpt|openai|claude(\s+code)?|anthropic|"
         r"gemini|copilot|llm|(a\s+)?(large\s+)?language\s+model|wordreport|python-docx)\b")
LABEL_PARAGRAPH = re.compile(
    r"^\W*("
    rf"(generated|created|written|produced|drafted)\s+(with|by|using)\s+{_TOOL}.{{0,80}}"
    rf"|(được\s+)?(tạo|soạn|viết|sinh)(\s+ra)?(\s+tự\s+động)?\s+(bởi|bằng|với)\s+{_TOOL}.{{0,60}}"
    rf"|nội\s+dung\s+(được\s+)?(tạo|sinh)\s+(bởi|bằng)\s+{_TOOL}.{{0,60}}"
    r"|ai[- ]generated(\s+content)?"
    r")\W*$",
    re.IGNORECASE,
)

# Trường trong app.xml tiết lộ trình tạo; đều là trường tuỳ chọn theo schema, Word tự điền lại khi lưu
APP_FIELDS_TO_DROP = ("Template", "TotalTime", "Application", "AppVersion", "Company", "Manager", "DocSecurity")


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")


def _clean_core(xml: bytes, author: str | None, report: list[str]) -> bytes:
    root = etree.fromstring(xml)

    def field(tag: str):
        prefix, local = tag.split(":")
        el = root.find(f"{prefix}:{local}", NS)
        if el is None:
            el = etree.SubElement(root, f"{{{NS[prefix]}}}{local}")
        return el

    creator = field("dc:creator")
    if author is not None:
        if creator.text != author:
            report.append(f"tác giả: '{creator.text or ''}' → '{author}'")
        creator.text = author
    elif creator.text and GENERATOR_PATTERN.search(creator.text):
        report.append(f"xoá tác giả là trình tạo: '{creator.text}'")
        creator.text = ""

    for tag in ("dc:description", "cp:keywords", "cp:category", "cp:contentStatus"):
        el = root.find(tag, NS)
        if el is not None and (el.text or "").strip():
            report.append(f"xoá {tag.split(':')[1]}: '{el.text.strip()}'")
            el.text = ""

    last = field("cp:lastModifiedBy")
    last.text = creator.text or ""
    field("cp:revision").text = "1"
    stamp = _now()
    for tag in ("dcterms:created", "dcterms:modified"):
        el = field(tag)
        el.set(f"{{{NS['xsi']}}}type", "dcterms:W3CDTF")
        el.text = stamp
    report.append("đặt lại ngày tạo/sửa, người sửa cuối, số lần sửa")
    return etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone=True)


def _clean_app(xml: bytes, report: list[str]) -> bytes:
    root = etree.fromstring(xml)
    for name in APP_FIELDS_TO_DROP:
        el = root.find(f"ep:{name}", NS)
        if el is not None:
            if (el.text or "").strip() and name in {"Application", "AppVersion", "Template", "Company"}:
                report.append(f"xoá {name}: '{el.text.strip()}'")
            root.remove(el)
    return etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone=True)


def _paragraph_text(p) -> str:
    return "".join(t.text or "" for t in p.iter(f"{{{NS['w']}}}t"))


def _clean_story(xml: bytes, part: str, report: list[str]) -> bytes:
    root = etree.fromstring(xml)
    removed = 0
    for p in list(root.iter(f"{{{NS['w']}}}p")):
        text = _paragraph_text(p).strip()
        if text and len(text) <= 160 and LABEL_PARAGRAPH.match(text):
            parent = p.getparent()
            # Ô bảng / header phải còn ít nhất một đoạn -> chỉ xoá chữ, giữ đoạn rỗng
            siblings = [c for c in parent if c.tag == p.tag]
            if parent.tag in {f"{{{NS['w']}}}tc", f"{{{NS['w']}}}hdr", f"{{{NS['w']}}}ftr"} and len(siblings) == 1:
                for r in list(p.iter(f"{{{NS['w']}}}r")):
                    r.getparent().remove(r)
            else:
                parent.remove(p)
            removed += 1
            report.append(f"xoá đoạn nhãn trong {part}: '{text}'")
    if not removed:
        return xml
    return etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone=True)


def _drop_thumbnail(files: dict[str, bytes], report: list[str]) -> None:
    rels = etree.fromstring(files["_rels/.rels"])
    for rel in list(rels):
        if rel.get("Type") == THUMBNAIL_REL:
            target = rel.get("Target").lstrip("/")
            rels.remove(rel)
            files.pop(target, None)
            report.append(f"xoá ảnh thu nhỏ của template: {target}")
    files["_rels/.rels"] = etree.tostring(rels, xml_declaration=True, encoding="UTF-8", standalone=True)


def remove_watermarks(src: str | Path, dst: str | Path | None = None, author: str | None = None) -> list[str]:
    """Làm sạch nhãn trình tạo/AI của một file .docx. Trả về danh sách thay đổi đã thực hiện.

    `dst` bỏ trống = ghi đè `src`. `author` đặt tác giả/người sửa cuối (None = giữ tác giả hiện có,
    trừ khi đó là tên thư viện/AI).
    """
    src = Path(src)
    dst = Path(dst) if dst else src
    report: list[str] = []

    with zipfile.ZipFile(src) as zin:
        infos = zin.infolist()
        files = {info.filename: zin.read(info.filename) for info in infos}

    if "docProps/core.xml" in files:
        files["docProps/core.xml"] = _clean_core(files["docProps/core.xml"], author, report)
    if "docProps/app.xml" in files:
        files["docProps/app.xml"] = _clean_app(files["docProps/app.xml"], report)
    for name in list(files):
        if re.fullmatch(r"word/(document|header\d*|footer\d*)\.xml", name):
            files[name] = _clean_story(files[name], name, report)
    if "_rels/.rels" in files:
        _drop_thumbnail(files, report)

    dst.parent.mkdir(parents=True, exist_ok=True)
    mode = src.stat().st_mode & 0o777  # file tạm được tạo với quyền 0600 -> trả lại quyền của file gốc
    with tempfile.NamedTemporaryFile(delete=False, suffix=".docx", dir=dst.parent) as tmp:
        tmp_path = Path(tmp.name)
    try:
        with zipfile.ZipFile(tmp_path, "w", zipfile.ZIP_DEFLATED) as zout:
            # [Content_Types].xml phải đứng đầu gói
            order = sorted(files, key=lambda n: (n != "[Content_Types].xml", n))
            for name in order:
                zout.writestr(name, files[name])
        tmp_path.chmod(mode)
        shutil.move(str(tmp_path), dst)
    finally:
        tmp_path.unlink(missing_ok=True)
    return report


def find_watermarks(path: str | Path) -> list[str]:
    """Liệt kê nhãn trình tạo/AI còn trong file (dùng cho lint), không sửa file."""
    found: list[str] = []
    with zipfile.ZipFile(path) as z:
        names = set(z.namelist())
        if "docProps/core.xml" in names:
            core = etree.fromstring(z.read("docProps/core.xml"))
            for tag in ("dc:creator", "dc:description", "cp:keywords", "cp:lastModifiedBy"):
                el = core.find(tag, NS)
                if el is not None and el.text and GENERATOR_PATTERN.search(el.text):
                    found.append(f"metadata {tag.split(':')[1]}: '{el.text}'")
        if "docProps/app.xml" in names:
            app = etree.fromstring(z.read("docProps/app.xml"))
            el = app.find("ep:Application", NS)
            if el is not None and el.text and GENERATOR_PATTERN.search(el.text):
                found.append(f"metadata Application: '{el.text}'")
        if "docProps/thumbnail.jpeg" in names:
            found.append("ảnh thu nhỏ của template (docProps/thumbnail.jpeg)")
        for name in sorted(names):
            if re.fullmatch(r"word/(document|header\d*|footer\d*)\.xml", name):
                root = etree.fromstring(z.read(name))
                for p in root.iter(f"{{{NS['w']}}}p"):
                    text = _paragraph_text(p).strip()
                    if text and len(text) <= 160 and LABEL_PARAGRAPH.match(text):
                        found.append(f"đoạn nhãn trong {name}: '{text}'")
    return found


def main(argv: list[str] | None = None) -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(prog="watermark-remover",
                                     description="Xoá nhãn công cụ/AI trong metadata và nội dung file .docx")
    parser.add_argument("files", nargs="+", help="File .docx (có thể nhiều file)")
    parser.add_argument("-o", "--output", help="File đầu ra (chỉ khi xử lý 1 file); mặc định ghi đè")
    parser.add_argument("--author", help="Đặt tên tác giả / người sửa cuối")
    parser.add_argument("--check", action="store_true", help="Chỉ liệt kê nhãn còn sót, không sửa file")
    args = parser.parse_args(argv)
    if args.output and len(args.files) > 1:
        parser.error("--output chỉ dùng khi xử lý một file")

    for name in args.files:
        if args.check:
            found = find_watermarks(name)
            print(f"{name}: {'sạch' if not found else f'{len(found)} nhãn'}")
            for item in found:
                print(f"  - {item}")
            continue
        changes = remove_watermarks(name, args.output, args.author)
        print(f"{args.output or name}: đã làm sạch ({len(changes)} thay đổi)")
        for change in changes:
            print(f"  - {change}")


if __name__ == "__main__":
    main()
