import zipfile

from docx import Document

from wordreport.inspector import lint_docx
from wordreport.watermark_remover import find_watermarks, main, remove_watermarks


def _labeled_doc(path):
    doc = Document()  # template python-docx: tác giả "python-docx", mô tả "generated by python-docx"
    doc.core_properties.keywords = "AI, LLM"
    doc.add_paragraph("Written by John Smith")
    doc.add_paragraph("Nội dung báo cáo thật.")
    doc.add_paragraph("🤖 Generated with [Claude Code](https://claude.com/claude-code)")
    doc.add_paragraph("Mô hình AI được tạo bởi nhóm để phân loại ảnh.")
    cell = doc.add_table(rows=1, cols=1).rows[0].cells[0]
    cell.paragraphs[0].add_run("Tạo bởi AI")
    doc.sections[0].footer.paragraphs[0].add_run("AI-generated content")
    doc.save(str(path))


def test_remove_watermarks_cleans_metadata_and_labels(tmp_path):
    src = tmp_path / "in.docx"
    _labeled_doc(src)
    found = find_watermarks(src)
    assert any("creator" in f for f in found) and any("thumbnail" in f for f in found)
    assert any("Generated with" in f for f in found)
    assert any(i.rule == "ai-label" for i in lint_docx(src))

    out = tmp_path / "out.docx"
    changes = remove_watermarks(src, out, author="Nguyễn Văn A")
    assert changes and find_watermarks(out) == []
    assert not any(i.rule == "ai-label" for i in lint_docx(out))

    doc = Document(str(out))
    texts = [p.text for p in doc.paragraphs]
    assert "Written by John Smith" in texts and "Nội dung báo cáo thật." in texts
    assert "Mô hình AI được tạo bởi nhóm để phân loại ảnh." in texts
    assert not any("Generated with" in t for t in texts)
    assert doc.tables[0].rows[0].cells[0].text == ""
    assert doc.sections[0].footer.paragraphs[0].text == ""
    props = doc.core_properties
    assert props.author == "Nguyễn Văn A" and props.last_modified_by == "Nguyễn Văn A"
    assert props.comments == "" and props.keywords == ""

    with zipfile.ZipFile(out) as z:
        names = z.namelist()
        app = z.read("docProps/app.xml").decode()
    assert names[0] == "[Content_Types].xml"
    assert "docProps/thumbnail.jpeg" not in names
    assert "<Application>" not in app and "<Template>" not in app
    assert src.read_bytes() != out.read_bytes()  # file gốc không bị ghi đè khi có -o


def test_cli_check_and_overwrite(tmp_path, capsys):
    path = tmp_path / "a.docx"
    _labeled_doc(path)
    main(["--check", str(path)])
    assert "nhãn" in capsys.readouterr().out
    main([str(path)])
    assert find_watermarks(path) == []
    main(["--check", str(path)])
    assert "sạch" in capsys.readouterr().out
